package com.dhu.lottery.model;

import java.util.Date;

public class LotteryRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.lotteryNo
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private String lotteryNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.firstDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer firstDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.secondDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer secondDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.thirdDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer thirdDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.fourthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer fourthDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.fifthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer fifthDigit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.number
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.createTime
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.sequenceOfToday
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Integer sequenceOfToday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_record.type
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.lotteryNo
     *
     * @return the value of t_lottery_record.lotteryNo
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public String getLotteryNo() {
        return lotteryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.lotteryNo
     *
     * @param lotteryNo the value for t_lottery_record.lotteryNo
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setLotteryNo(String lotteryNo) {
        this.lotteryNo = lotteryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.firstDigit
     *
     * @return the value of t_lottery_record.firstDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getFirstDigit() {
        return firstDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.firstDigit
     *
     * @param firstDigit the value for t_lottery_record.firstDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setFirstDigit(Integer firstDigit) {
        this.firstDigit = firstDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.secondDigit
     *
     * @return the value of t_lottery_record.secondDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getSecondDigit() {
        return secondDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.secondDigit
     *
     * @param secondDigit the value for t_lottery_record.secondDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setSecondDigit(Integer secondDigit) {
        this.secondDigit = secondDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.thirdDigit
     *
     * @return the value of t_lottery_record.thirdDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getThirdDigit() {
        return thirdDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.thirdDigit
     *
     * @param thirdDigit the value for t_lottery_record.thirdDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setThirdDigit(Integer thirdDigit) {
        this.thirdDigit = thirdDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.fourthDigit
     *
     * @return the value of t_lottery_record.fourthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getFourthDigit() {
        return fourthDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.fourthDigit
     *
     * @param fourthDigit the value for t_lottery_record.fourthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setFourthDigit(Integer fourthDigit) {
        this.fourthDigit = fourthDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.fifthDigit
     *
     * @return the value of t_lottery_record.fifthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getFifthDigit() {
        return fifthDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.fifthDigit
     *
     * @param fifthDigit the value for t_lottery_record.fifthDigit
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setFifthDigit(Integer fifthDigit) {
        this.fifthDigit = fifthDigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.number
     *
     * @return the value of t_lottery_record.number
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.number
     *
     * @param number the value for t_lottery_record.number
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.createTime
     *
     * @return the value of t_lottery_record.createTime
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.createTime
     *
     * @param createTime the value for t_lottery_record.createTime
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.sequenceOfToday
     *
     * @return the value of t_lottery_record.sequenceOfToday
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Integer getSequenceOfToday() {
        return sequenceOfToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.sequenceOfToday
     *
     * @param sequenceOfToday the value for t_lottery_record.sequenceOfToday
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setSequenceOfToday(Integer sequenceOfToday) {
        this.sequenceOfToday = sequenceOfToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_record.type
     *
     * @return the value of t_lottery_record.type
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_record.type
     *
     * @param type the value for t_lottery_record.type
     *
     * @mbggenerated Sun Jan 22 04:24:29 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }
}