package com.dhu.lottery.model;

public class LotteryRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_rule.ruleCode
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    private String ruleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_rule.ruleName
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_rule.ruleDesc
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    private String ruleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lottery_rule.number
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_rule.ruleCode
     *
     * @return the value of t_lottery_rule.ruleCode
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public String getRuleCode() {
        return ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_rule.ruleCode
     *
     * @param ruleCode the value for t_lottery_rule.ruleCode
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_rule.ruleName
     *
     * @return the value of t_lottery_rule.ruleName
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_rule.ruleName
     *
     * @param ruleName the value for t_lottery_rule.ruleName
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_rule.ruleDesc
     *
     * @return the value of t_lottery_rule.ruleDesc
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public String getRuleDesc() {
        return ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_rule.ruleDesc
     *
     * @param ruleDesc the value for t_lottery_rule.ruleDesc
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lottery_rule.number
     *
     * @return the value of t_lottery_rule.number
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lottery_rule.number
     *
     * @param number the value for t_lottery_rule.number
     *
     * @mbggenerated Sun Jan 22 04:41:21 CST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}